# Generated by Django 5.1.5 on 2025-01-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0007_alter_tag_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag']},
        ),
        migrations.AlterField(
            model_name='joke',
            name='tags',
            field=models.ManyToManyField(blank=True, to='jokes.tag'),
        ),
    ]
